
- name: Change root password
  when: users.root is defined
  user:
    name: root
    password: "{{ users.root.0 }}"
    update_password: always

- name: Create local users
  become: true
  when: ssh.users is defined and ssh.passwords is defined
  user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    state: present
    shell: /bin/bash   
  with_together:
    - "{{ users.logins }}"
    - "{{ users.passwords }}"

