---
- name: Enable root ssh
  become: true
  when: 
    - "'allowrootlogin' in openssh"
    - openssh.allowrootlogin == true | default 
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin prohibit-password'
    line: 'PermitRootLogin yes'
  notify:
  - restart ssh

