---
- name: Enable root ssh
  become: true
  when: openssh.allowrootlogin == "Yes"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin without-password'
    line: 'PermitRootLogin yes'
  notify:
  - restart ssh

