---
- name: Enable & Blacklist All
  ufw:
    state: enabled
    policy: reject

- name: Whitelist IP addrs
  ufw:
    rule: allow
    src: "{{ item }}"
  loop:
    "{{ ufw.ips }}"
  notify:
  - restart ufw

