---

- name: Install MySQL
  apt:
    name: ["mysql-server", "python3-pymysql"]
    update_cache: yes
    state: present

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql.root.0 }}"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop:
    - '127.0.0.1'
    - 'localhost'
  become: yes
  notify: Restart MySQL

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  notify: Restart MySQL

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql.root.0 }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql.root.0 }}"

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true




#- name: Set MySQL root password
#  when: mysql.root is defined
#  mysql_user: 
#    name: root 
#    password: "{{ mysql.root.0 }}"
#    priv: "*.*:ALL,GRANT"
#    login_unix_socket: "/var/run/mysqld/mysqld.sock"

# - name: Copy my.cnf file
#   when: mysql.root is defined
#   template:
#     src: "my.cnf.j2"
#     dest: "~/.my.cnf"
#     owner: root
#     mode: 0600

- name: Copy MySQL database dumps
  copy:
    src: "{{item}}.sql.gz"
    dest: /tmp
  with_items: "{{mysql.db}}"

- name: Import MySQL databases
  mysql_db:
    name: "{{item}}"
    state: import
    target: "/tmp/{{item}}.sql.gz"
  with_items: "{{mysql.db}}"

- name: Delete MySQL database dumps
  file:
    path: "/tmp/{{item}}.sql.gz"
    state: absent
  with_items: "{{mysql.db}}"

#- name: Create MySQL DB user(s)
#  when: mysql.users is defined and mysql.passwords is defined
#  mysql_user: 
#    name: "{{ item.0 }}" 
#    password: "{{ item.1 }}"
#    priv: '*.*:ALL' 
#    state: present
#  with_together:
#    - "{{ mysql.users }}" 
#    - "{{ mysql.passwords }}"
 
